# Generated by Django 5.2.6 on 2025-09-25 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Biblioteca', '0001_initial'),
        ('Livros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacoes',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='id_livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livros.livros'),
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidos_extensao',
            name='id_emprestimo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.emprestimos'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livros.livros'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
