# Generated by Django 5.2.6 on 2025-10-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateField(auto_now=True),
        ),
    ]
