# Generated by Django 5.2.6 on 2025-09-25 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_genero', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('autor', models.CharField()),
                ('editora', models.CharField()),
                ('descricao', models.TextField()),
                ('data_publicacao', models.DateField()),
                ('imagem', models.ImageField(null=True, upload_to='')),
                ('status', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Livros_Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livros.generos')),
                ('id_livros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livros.livros')),
            ],
        ),
    ]
