# Generated by Django 5.2.6 on 2025-09-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
    ]
