# Generated by Django 5.2.6 on 2025-10-20 18:50

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('method', models.CharField(choices=[('card', 'Cartão'), ('pix', 'Pix')], max_length=10)),
                ('status', models.CharField(choices=[('pendding', 'Pendente'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pix_code', models.TextField(blank=True, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
