# Generated by Django 5.2.6 on 2025-10-20 18:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multa',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='card_last4',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='method',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='pix_code',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='status',
        ),
        migrations.AddField(
            model_name='multa',
            name='data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='multa',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='multa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multa',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('method', models.CharField(choices=[('pix', 'Pix'), ('card', 'Cartão')], default='pix', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('pix_code', models.TextField(blank=True, null=True)),
                ('multa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Multas.multa')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
