# Generated by Django 5.2.6 on 2025-10-20 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0004_alter_emprestimos_data_emprestimo_and_more'),
        ('Multas', '0002_remove_multa_amount_remove_multa_card_last4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='multa',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AddField(
            model_name='payment',
            name='emprestimo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Biblioteca.emprestimos'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Multa',
        ),
    ]
