# Generated by Django 5.2.6 on 2025-10-31 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0004_alter_emprestimos_data_emprestimo_and_more'),
        ('Livros', '0002_alter_livros_imagem'),
        ('Multas', '0003_remove_payment_multa_alter_payment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultaLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_livro_copia', models.CharField(max_length=255)),
                ('autor_livro_copia', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('id_livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Livros.livros')),
            ],
        ),
        migrations.CreateModel(
            name='Multas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario_copia', models.CharField(help_text='Nome do usuário no momento da emissão', max_length=255)),
                ('cpf_usuario_copia', models.CharField(help_text='CPF do usuário no momento da emissão', max_length=14)),
                ('valor_multa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pagamento pendente'), ('PAGO', 'Pagamento concluído')], default='PENDENTE', max_length=10)),
                ('id_emprestimo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Biblioteca.emprestimos')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('livros_a_pagar', models.ManyToManyField(through='Multas.MultaLivro', to='Livros.livros')),
            ],
        ),
        migrations.AddField(
            model_name='multalivro',
            name='id_multa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Multas.multas'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AlterUniqueTogether(
            name='multalivro',
            unique_together={('id_multa', 'id_livro')},
        ),
    ]
