# Generated by Django 5.2.6 on 2025-11-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multas', '0004_multalivro_multas_multalivro_id_multa_delete_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multas',
            name='preference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
