# Generated by Django 5.2.6 on 2025-09-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default='asda'),
            preserve_default=False,
        ),
    ]
