# Generated by Django 5.2.6 on 2025-10-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_usuario_imagem'),
        ('User', '0004_alter_usuario_username'),
    ]

    operations = [
    ]
